webex/widgets

- package-lock.json
- package.json
- release.config.js
- rollup.config.js
I have the tested the `esm` bundle on CRA already.
> Exclude webex from the bundle

- .gitignore
Sourcemap was being gitignored via the `*.map` line.
> Add missing docs sourcemap

- package-lock.json
- package.json
- src/widgets/WebexMeeting/WebexMeeting.jsx
This PR updates the webex component system dependencies to the latest versions with better meetings support.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-174911
> Update Components, Adapter, and Webex SDK

- package-lock.json
- package.json
Update components dependencies to version 1.60.0
> build(package): update components to v1.60.0

- src/widgets/WebexMeeting/WebexMeeting.jsx
Update the controls in the meeting widget by passing a custom control list to the widget's Meeting component.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-220022
Depends on: https://github.com/webex/widgets/pull/32
> refactor(WebexMeeting): update meeting widget controls

- tests/WebexMeeting.e2e.js
- tests/pages/MeetingWidget.page.js
Create a E2E test to assert user can mute audio before joining a meeting via meetings widget
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223786
> test(WebexMeeting): e2e test mute audio before join

- wdio.conf.js
Configure WebdriverIO to also run end to end tests on MicrosoftEdge
This should be merge after we merge PR https://github.com/webex/widgets/pull/47
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-226579
> test(webdriverio): add MicrosoftEdge capability

- tests/WebexMeeting.e2e.js
- tests/pages/MeetingWidget.page.js
Create a E2E test to assert user can leave a meeting via meetings widget
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223793
> test(WebexMeeting): e2e test leave the meeting

- package-lock.json
- package.json
Updated version of sdk component adapter in package.json to v1.33.2.
> build(package): update sdk component adapter to v1.33.2

- tests/WebexMeeting.e2e.js
Load/unload Meeting Widget once for all current E2E tests
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-231427
> test(WebexMeeting): load/unload meeting widget once for all tests

- package-lock.json
- package.json
- wdio.conf.js
Source both .env and .env.default when running E2E tests
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-231500
> build(e2e): read E2E environment variables from .env.default

- .env.default
- wdio.conf.js
Give the ability to specify on which browser to run the E2E test  
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-231502
> build(e2e): configure on which browsers to run E2E tests

- tests/WebexMeeting.e2e.js
- tests/util.js
Skip test user/room creation when access token/destination are provided.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-231496
> test(WebexMeeting): skip user/room creation if token/destination exist

- .github/workflows/update-dependencies.yml
As we include interfaces as a dependency we need also to add the workflow for this.
https://github.com/webex/widgets/pull/55/commits/ad783316afe5423ea4a2dba141d7bcaa98063790
> build(workflow): update dependency on event

- src/widgets/WebexMeeting/WebexMeeting.jsx
Use withAdapter HOC in the meeting widget
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-228361
> refactor(WebexMeeting): use withAdapter HOC in WebexMeeting widget

- .circleci/config.yml
Run E2E tests on every PR and every release 
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223798
> build(Tests): include e2e tests in pipeline process

- package-lock.json
- package.json
- src/widgets/WebexMeeting/WebexMeeting.css
- src/widgets/WebexMeeting/WebexMeeting.jsx
- tests/pages/MeetingWidget.page.js
Add WebexMeetingControls under the meeting and roster components
> refactor(WebexMeeting): add controls under meeting and roster

- package-lock.json
- package.json
Increase sdk component adapter version from 1.33.4 to 1.36.0
> fix(package): update sdk component adapter to v1.36.0

- package-lock.json
- package.json
Updated version of sdk component adapter in package.json to v1.36.1.
> build(package): update sdk component adapter to v1.36.1

- src/widgets/WebexMeeting/WebexMeeting.jsx
task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-251739
> feat(WebexWidget): display media access based on permissions

- demo/WebexMeetingWidgetDemo.jsx
- demo/WebexMeetingWidgetDemo.scss
- src/widgets/WebexMeeting/WebexMeeting.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-253309
> feat(WebexMeeting): add className and style as props

- webpack.config.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-263965
> feat(webpack): configure webpack to load gif files

- demo/App.jsx
- demo/App.scss
- demo/WebexMeetingWidgetDemo.jsx
- demo/WebexMeetingWidgetDemo.scss
- src/widgets/WebexMeeting/WebexMeeting.css
- src/widgets/WebexMeeting/WebexMeeting.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-264469
> feat(WebexMeeting): make widget occupy all available vertical space

- demo/WebexMeetingWidgetDemo.jsx
- demo/WebexMeetingWidgetDemo.scss
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-261595
> feat(WebexWidget): add theme selector on the widgets demo page

- package-lock.json
- package.json
Update sdk-component-adapter to 1.63.0
> fix(package): update sdk-component-adapter to 1.63.0

- src/widgets/WebexMeeting/WebexMeeting.css
Resize meeting on mobile.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-270769
> fix(WebexMeeting): resize meeting on mobile

- tests/WebexMeeting.e2e.js
- tests/pages/MeetingWidget.page.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-278693
> feat(tests): add join with media e2e test

- package-lock.json
- package.json
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284127
> fix(package): update js-sdk to 1.149.2

- demo/App.jsx
- demo/App.scss
- demo/WebexMeetingWidgetDemo.jsx
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284125
> fix(WebexMeeting): add style scoping to setup form and section

- package-lock.json
- package.json
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284712
> fix(package): move momentum ui from dependencies to dev dependecies

- package.json
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-284694
> fix(package): bump react version to ^17.0.2

- src/widgets/WebexMeeting/WebexMeeting.css
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-285590
> fix(WebexMeeting): set min-width on the meeting widget to 18.5rem

- demo/WebexMeetingWidgetDemo.jsx
- demo/WebexMeetingWidgetDemo.scss
- src/widgets/WebexMeeting/WebexMeeting.jsx
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-289116
> feat(WebexMeeting): add layoutType prop for meeting's remote video

- package-lock.json
- package.json
- rollup.config.js
Updating the CSS bundle and CSS file name to match what Components package.
> Move CSS bundle into CSS folder

- README.md
Meetings widget is now generally available 🥳
> docs(readme): remove beta status section. Meetings widget is GA 🎉

- src/widgets/WebexMeetings/README.md
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-286745
> docs(Readme): document Firefox concurrent microphones issue

- src/widgets/WebexMeetings/README.md
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-288752
> docs(Readme): add note for share screen issue on some browsers

- README.md
- demo/App.jsx
- demo/WebexMeetingsWidgetDemo.jsx
- package-lock.json
- package.json
- src/widgets/WebexMeetings/WebexMeetings.jsx
[SPARK-312429](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-312429)
> add option to enable fedramp

- demo/WebexMeetingsWidgetDemo.jsx
- demo/WebexMeetingsWidgetDemo.scss
- src/widgets/WebexMeetings/README.md
Task link: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-292891
> docs(WebexMeetingsWidgetDemo): add warning note for known Safari issue

- package-lock.json
- package.json
**Description of changes made (Required)**
As part of SPARK-426299, Upgrade the widgets with latest SDK, components
**Associated JIRA (Required)**
JIRA
[SPARK-426299](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-426299)
**Relevant UI (Optional)**
https://app.vidcast.io/share/3bb6a78a-a309-44c4-a3bd-179e1f61f3f3
> chore(sdk): upgrade the widgets with latest SDK version

- package-lock.json
- package.json
**Description of changes made (Required)**
As part of SPARK-440622, moving the Webex to dependencies
**Associated JIRA (Required)**
JIRA
[SPARK-440622](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-440622)
**Relevant UI (Optional)**
N/A
> fix(sdk): move the webex to dependencies in widgets

- package-lock.json
- package.json
**Description**
Upgrade the components version which contains the fix to allow remote video be a draggable element.
**JIRA** - [SPARK-409279](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-409279)
> fix: upgrade @webex/components version

- package-lock.json
- package.json
Fixes the intermittent issue where a user was auto-leaving the meeting even without joining it.
JIRA - [SPARK-379330](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-379330)
> fix(meetings): fix intermittent auto leave meeting issue

- demo/WebexMeetingsWidgetDemo.jsx
- demo/WebexMeetingsWidgetDemo.scss
- package-lock.json
- package.json
- src/widgets/WebexMeetings/WebexMeetings.jsx
- tests/util.js
Description: 
Modified the space ID code within the meetings widget to throw an error when a room ID is provided. 
Default values for enableUnifiedMeetings and enableAdhocMeetings have been set to true. 
Configuration changes are now migrated to V2 meetings. 
Additionally, updated the demo samples and test cases.
> feat(meetings): space id code change in meetings widget

- CONTRIBUTING.md
Updating the missing step for linking dependent repo's locally
> docs(contributing-guide): Update CONTRIBUTING.md

- package.json
One of the babel packages seems to be causing build failure
> fix(meeting): fixing build error

- package-lock.json
- package.json
Updated sdk-component-adapter and components version where changes for captcha flow were added.
JIRA: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-521834 
Screen Recording:
https://github.com/webex/widgets/assets/65543166/c5d0ff26-a1c4-43e5-ba28-1cae38d1b166
> fix(meeting): added captcha flow

- package-lock.json
- package.json
Issue: Not showing password popup when click join meeting after dismissing initial popup.
Fix: added condition to check passwordRequired and empty options to updateMeeting with passwordRequired true
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-557507
> fix: updated sdk-component-adapter to latest to fix joinMeeting

- packages/contact-center/store/release.config.js
Fix tag on which publish is made
> fix(release): fix-npm-tag

- .coderabbit.yaml
Create CodeRabbitAI configuration file for widgets branch
> chore(coderabbit): create .coderabbit.yaml

- packages/contact-center/cc-components/src/components/UserState/user-state.tsx
- packages/contact-center/task/src/CallControl/call-control.presentational.tsx
- packages/contact-center/task/src/TaskList/task-list.presentational.tsx
- packages/contact-center/task/src/helper.ts
- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- New UI for task list and call controls
- Updates user state if state is wrap up
https://github.com/user-attachments/assets/9badb2dc-7d27-47c8-aa0e-0f6254640f87
> fea(cc-task): new ui for task list and call controls

- packages/contact-center/CONTRIBUTING.md
- widgets-samples/cc/samples-cc-react-app/webpack.config.js
- Add HMR in react-samples app
-We can make changes and let the application reload and show the new UI
- any change in tsx/ts/js/jsx file will cause a full reload
- any change in scss or css file will not cause a reload and the changes will appear directly
-- https://app.vidcast.io/share/f5ea70e4-15a1-486b-8984-a642f675f9a3
-Made changes in the react-app and let app reload
-Made changes in the user-state UI component and let app reload(both tsx and scss file)
##CAVEAT
-https://app.vidcast.io/share/44f6fd3d-5cd8-481c-b04c-f311c3cb2b53
- Right now if we make changes in the scss of station-login, then that change will not be reflected, but since we are moving all the components to the cc-components, I'm not worrying about this because once the component is present in the cc-components then …
> fix(tooling): Implement-HMR-in-react-samples-app

- packages/contact-center/task/src/CallControl/call-control.presentational.tsx
- packages/contact-center/task/src/CallControl/call-control.styles.scss
- packages/contact-center/task/tests/CallControl/call-control.presentational.tsx
- packages/contact-center/task/tests/CallControl/index.tsx
- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- widgets-samples/cc/samples-cc-wc-app/app.js
https://app.vidcast.io/share/2b6a8be0-f839-4e35-be73-a7f8006cf3f3
> feat(cc-widgets): added new UI for call controls

- package.json
- packages/contact-center/station-login/tests/helper.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- packages/contact-center/task/src/helper.ts
- packages/contact-center/task/src/task.types.ts
- packages/contact-center/task/tests/helper.ts
- widgets-samples/cc/samples-cc-react-app/src/App.scss
- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- widgets-samples/cc/samples-cc-wc-app/app.js
- Send out currentTask and wrapUpReason onWrapUp
https://app.vidcast.io/share/97ca6ab9-8b15-4f9a-8792-0578ca0654d3
Updated the document here with required scenario: https://confluence-eng-gpk2.cisco.com/conf/x/PX4NJ. Have added it under the Agent State section. Will move it to Call Controls once we have them added to the test plan documentation
> fix(cc-task): onWrapUp with task object and reason for wrapup

- packages/contact-center/store/package.json
- packages/contact-center/store/src/storeEventsWrapper.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- yarn.lock
* Widgets `wrapup` was broken due to using the latest SDK version
* This PR fixes that by making required widget changes.
> fix(widgets): fixed-wrapup-issue

- .github/PULL_REQUEST_TEMPLATE.md
Update the pull request template to include the GAI policy
> chore(pulls): update gai policy in the template

- .github/PULL_REQUEST_TEMPLATE.md
Update Pull request template for master branch with GAI policy
> chore(pulls): update pull request for master

- packages/contact-center/cc-components/src/components/task/IncomingTask/incoming-task.tsx
- packages/contact-center/cc-components/src/components/task/Task/index.tsx
- packages/contact-center/cc-components/src/components/task/Task/styles.scss
- packages/contact-center/cc-components/src/components/task/task.types.ts
- packages/contact-center/cc-components/src/wc.ts
- packages/contact-center/cc-widgets/src/wc.ts
- packages/contact-center/store/src/store.ts
- packages/contact-center/store/src/store.types.ts
- packages/contact-center/store/src/storeEventsWrapper.ts
- packages/contact-center/store/tests/store.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- packages/contact-center/task/src/IncomingTask/index.tsx
- packages/contact-center/task/src/helper.ts
- packages/contact-center/task/src/task.types.ts
- packages/contact-center/task/tests/IncomingTask/index.tsx
- packages/contact-center/task/tests/helper.ts
- widgets-samples/cc/samples-cc-react-app/src/App.scss
- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- Supports multiple incoming task
- Removed incoming task state from store, now the incoming tasks should be handled on the application
- Devs can render multiple incoming tasks at their desired location in their application
https://github.com/user-attachments/assets/d60c2980-d6ad-4614-a6f6-cca6d84b63f6
- Testing video attached above
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.
> fix(incoming-task): support multiple incoming tasks

- packages/contact-center/store/src/store.ts
- packages/contact-center/store/src/store.types.ts
- packages/contact-center/store/src/storeEventsWrapper.ts
- packages/contact-center/store/tests/store.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- widgets-samples/cc/samples-cc-react-app/src/App.scss
- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- Adds a new property in store called agentProfile which will help EPIC to quickly look up information about the agent
- A new property is present in the store (store.agentProfile), which will give devlopers information about the agent
- https://app.vidcast.io/share/1d4e149b-a5b4-4545-8e6a-6128b649cb73
---
> fix(store): add agent profile in store

- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- widgets-samples/cc/samples-cc-react-app/src/EngageWidget.css
- widgets-samples/cc/samples-cc-react-app/src/EngageWidget.tsx
Adding digital channels support in sample app 
added engage widgets logic in sample app to load imi widgets
< DESCRIBE YOUR CHANGES >
added engage widgets logic in sample app to load imi widgets
https://app.vidcast.io/share/b419d453-2d4c-4fc2-8bb6-961b04cbcd43
new vidcast: https://app.vidcast.io/share/76f7d037-f99b-417f-a370-50f1ca1524f3
Initiate chat and accept in widgets sample app. the chat should be loaded.
Initiate email and accept in in widgets sample app. the email should be loaded.
reload the app and selected widgets should be loaded.
---
> feat(cc-widgets): Digital channels support

- packages/contact-center/cc-components/src/components/task/task.types.ts
- packages/contact-center/cc-widgets/src/wc.ts
- packages/contact-center/store/package.json
- packages/contact-center/store/src/store.types.ts
- packages/contact-center/store/src/storeEventsWrapper.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- packages/contact-center/task/src/CallControl/index.tsx
- packages/contact-center/task/src/CallControlCAD/index.tsx
- packages/contact-center/task/src/helper.ts
- packages/contact-center/task/src/task.types.ts
- packages/contact-center/task/tests/helper.ts
- widgets-samples/cc/samples-cc-react-app/package.json
- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- widgets-samples/cc/samples-cc-wc-app/app.js
- widgets-samples/cc/samples-cc-wc-app/index.html
- yarn.lock
* Either there aren't callbacks for certain actions or there's no data passed
* onTaskSelected needed to know if it was programmatic or clicked
* By adding data to callbacks wherever necessary
* Updating their Typedoc
* Adding the same in the React Sample App
* Changing event names for Hold/UnHold & Pause/Resume Recording that were changed in SDK earlier
- [CAI-6283: Adding callback and data wherever necessary](https://app.vidcast.io/share/06a79baf-3894-45d0-9c82-ce19166e2163)
- [onTaskSelected onClick Boolean and full round testing](https://app.vidcast.io/share/12c58d67-3d90-432a-8a9f-bb82819e1ba3)
* Tested all the call backs in multi session to see if we get the right data
* Because we upgraded the SDK
* Tested Station Login error handling for Extension in use and invalid DN number
* …
> fix(cc-task): add required callbacks

- packages/contact-center/store/package.json
- yarn.lock
Updates SDK version to incorporate https://github.com/webex/webex-js-sdk/pull/4353
We dont send TASK_HYDRATE if the task is already present in the taskCollection
We send TASK_INCOMING if the task is not in taskCollection and task's state is new
We send TASK_HYDRATE of the task is not in taskCollection and state is connected
- https://app.vidcast.io/share/d639ad00-b941-4e3c-a50b-6a33aeef3023
-
---
> fix(store): incorporate task hydrate fix from SDK

- copy_to_docs.sh
- playwright/constants.ts
- widgets-samples/chat-client-e2e.html
creating a new chat client for e2e tests
added new chat-client file and updated url
---
> fix(cc-widgets): E2e tests config updated with new dedicated chat url

- packages/contact-center/ui-logging/package.json
- add publishConfig in cc-ui-logging package
allow npm public publish
---
> fix(ui-logging): add public access config in cc-ui-logging

- .releaserc
Force publish verison 1.28.0-ccwidgets.108, due to cc-ui-componenet not have proper publishconfig.
- We will force publish version 108 and then revert these changes.
---
> fix(publish): force-publish-version-108

- .releaserc
Force publish verison 1.28.0-ccwidgets.108, due to cc-ui-componenet not have proper publishconfig.
- We will force publish version 108 and then revert these changes.
---
> fix(tooling): force publish version 108 - 2

- .releaserc
removes changes for force publish of v108
Reverting semanticrelease.rc 
---
> fix(tooling): remove changes for force publishing v108

- .releaserc
Remove semantic-release exec to only publish a tag
---
> fix(tooling): force publish tag

- .releaserc
- This PR reverts the changes made in PR 527 to only publish tag
The pipeline will be restored. With all the packages published
---
> fix(tooling): revert removed code for publishing tag

- packages/contact-center/store/package.json
- yarn.lock
Vidcast link: https://app.vidcast.io/share/95b94fdc-4a90-431e-9344-9400e5f97dd3
This PR is in continuation to the CC SDK PR:   [webex/webex-js-sdk/pull/4454](https://github.com/webex/webex-js-sdk/pull/4454)  
This PR addresses the undefined product issue encountered while submitting metrics. The fix was implemented by adding the missing definitions for the behavioral events AGENT_CONTACT_ASSIGN_FAILED and AGENT_INVITE_FAILED in behavioral-events.ts within the CC SDK
Updated "@webex/contact-center" version from 3.8.1-next.34 to 3.8.1-next.41 to include the latest fixes and enhancements.
---
> fix(submit-metricst): fix-for-the-product-undefined-issue
