- .circleci/config.yml
- .nvmrc
- package-lock.json
- package.json
When a user leaves the meeting, a message stating that the meeting has ended is displayed, instead of sending back the user to the interstitial page.
This prevents issues with meeting controls getting out of sync when the meeting no longer exists, and simplifies the workflow for applications embedding the widget.
Other updates:
- Updating node version and node sass, the demo app wasn't loading as there was a mismatch between the node sass version in the dev dependencies and the node version of the project
> Update to flow when leaving a meeting

- package-lock.json
- package.json
- src/widgets/WebexMeeting/WebexMeeting.jsx
Create the meeting object and provide the meeting id to the meeting component, by using the withMeeting HOC in WebexMeetingWidget.
Link Jira: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223898
Depends on: #39
> refactor(WebexMeeting): use withMeeting HOC in WebexMeeting widget

- tests/WebexMeeting.e2e.js
- tests/pages/MeetingWidget.page.js
Create a E2E Test to Assert User Waits for Others After Joining a Meeting via Meetings Widget.
https://jira-eng-gpk2.cisco.com/jira/secure/Dashboard.jspa
> test(WebexMeeting): e2e test waiting for others after join

- tests/WebexMeeting.e2e.js
Create a E2E test to assert user can mute audio after joining a meeting via meetings widget
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223795
> test(WebexMeeting): e2e test mute audio after join

- tests/WebexMeeting.e2e.js
- tests/pages/MeetingWidget.page.js
Create a E2E test to assert user can disable video before joining a meeting via meetings widget
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223787
> test(WebexMeeting): e2e test mute video before join

- tests/WebexMeeting.e2e.js
- tests/pages/MeetingWidget.page.js
Create a E2E test to assert user can mute video after a meeting via meetings widget
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-223796
> test(WebexMeeting): e2e test mute video after join

- package-lock.json
- package.json
- src/widgets/WebexMeeting/WebexMeeting.css
- src/widgets/WebexMeeting/WebexMeeting.jsx
Use the member roster component in the meeting widget. Show/hide when the participants control is clicked.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-227951
> feat(WebexMeeting): add roster component in meeting widget

- tests/WebexMeeting.e2e.js
- tests/pages/MeetingWidget.page.js
In order to align with the changes made in WebexMeeting widget, it was necessary to update the name of the class that stylizes the widget. Additionally  it was necessary to give up to the nesting if structure from afterAll, because now the creation of a room no longer depends on the creation of a user.
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-233689
> fix(WebexMeeting): fix e2e tests

- rollup.config.js
Without the `babelrc` flag, babel plugin for rollup ignores the babel presets configured in `package.json`. This results in inaccurately transpiled ESM bundles.
> build(rollup): use babelrc

- tests/WebexMeeting.e2e.js
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-230993
&
https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-230994
> feat(tests): assert media is muted after joining the meeting

- demo/WebexMeetingsWidgetDemo.jsx
Description: 
fix the broken link for migration guide
Fix the space ID Error Message where the link is broken for the migration guide for widget and JS SDK
Old migration guide link -
https://github.com/webex/webex-js-sdk/wiki/Migration-guide-for-USM-meeting
New migration guide link -
https://github.com/webex/webex-js-sdk/wiki/Migration-to-Unified-Space-Meetings
> fix(meetings): fix the broken link for migration guide

- package.json
Upgrading sdk-component-adpater repo version to the latest to include the password flow for the guest user.
Testcase 1: The guest joins the meeting by entering the password.
Testcase 2: The guest joins the meeting as host by entering the host key
https://github.com/webex/widgets/assets/65543166/381bc96d-d55c-43e4-a411-4150d5e9b68c
Testcase 3: Host joins with host access token without a password prompt.
https://github.com/webex/widgets/assets/65543166/135cf872-4e0c-43e1-a0ec-3317c45ac45d
> fix(meeting): updated sdkcomponentadapter version to add password flow

- package.json
After upgrading to node 20, the demo build failed in the circle ci pipeline due to Webpack incompatibility with the latest version. Added Backward Compatibility Flag as temporary workaround for now. In the meantime will try to upgrade webpack version and see if it still works.
Ran the build command.
Ran npm start
Ran npm run demo:build
All the command works.
> fix(tooling): fixed the demo build

- package-lock.json
- package.json
- webpack.config.js
Putting permanent fix for demo:build issue. Upgraded webpack and included polyfills
> fix(tooling): upgraded webpack packages and included polyfills

- demo/App.jsx
- package-lock.json
- package.json
Upgrade React version to 18.3.1 as 17.0.2 has been out of support for a couple of years now and the older react version is causing problems while developers try to build new applications.
Jira link: [SPARK-551578](https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-551578)
PR related to this on @webex/components - https://github.com/webex/components/pull/842
Vidcast for the demo: https://app.vidcast.io/share/c5ffc9af-b4c3-4079-bcf0-db428fde5073
> feat(react): upgrade react to 18.3.1

- package-lock.json
- package.json
Issue: Meeting name not showing in meeting widget instead it shows sip address.
Fix: added update title code in fetchMeetingInfo.topic and added meetingInfo component to in-meeting component
> fix: updated components and sdk-component-adapter to fix Meeting Name

- package-lock.json
- package.json
issue: meeting title alignment is not correct in in-meeting screen in meetings widget.
Fix: updated margin in components package and updated widgets with the latest version of components.
SS before:
SS After:
> fix: updated components to 1.275.2 fix meeting title margin

- package-lock.json
- package.json
Upgrading the webex to newer-version which is 2.x version and the sdk-component-adapter to the newer-version as well which is 1.112.x version
- This Upgrading `webex` to newer-version is because of the fix that was made in [SDK](https://github.com/webex/webex-js-sdk/pull/3902) that needs to be in widgets 
- So the fix is about the user trying to `joinmeeting` by entering the name according to their wish but unfortunately, the user entered name was not reflected on the remote side of the meeting rather it printed the system default name so SDK fix will give the solution in the widgets that is why the `webex` is needed to upgrade in the widgets to reflect the changes that made in SDK
- Also upgrading the `sdk-component-adapter` to new version in widgets because whatever the fix does on the …
> fix(webex): upgrading webex to new-version

- packages/contact-center/store/src/store.ts
During testing, we unintentionally published npm versions 1.28.0-wxcc.1 and 1.28.0-wxcc.2. Since npm does not allow overwriting existing versions, we need to continue publishing from 1.28.0-wxcc.3.
Semantic Release relies on GitHub releases to determine the next version. To ensure the versioning aligns correctly, this PR is necessary to create a GitHub release for version 1.28.0-wxcc.2. This step helps maintain consistency between npm and GitHub versioning.
> fix(release): trigger-wxcc-2-release-on-github

- .releaserc
During testing, we unintentionally published npm versions 1.28.0-wxcc.1 and 1.28.0-wxcc.2. Since npm does not allow overwriting existing versions, we need to continue publishing from 1.28.0-wxcc.3.
**We have published release 1.28.0-wxcc.2 https://github.com/webex/widgets/pull/333. Now we need to start publishing our changes onto npm, so we are adding back the publishing step**
Semantic Release relies on GitHub releases to determine the next version. To ensure the versioning aligns correctly, this PR is necessary to create a GitHub release for version 1.28.0-wxcc.2. This step helps maintain consistency between npm and GitHub versioning.
> fix(release): add-publish-step-in-tooling

- .circleci/config.yml
- .releaserc
For publishing, we have our own custom logic, while publishing we consider the branch name as the tag . See below 
Since the branch name is feat/cc-widgets, we published it onto feat/cc-widgets tag. 
We will update the circle ci and releaserc to run on new branch name i.e wxcc. And the name branch name i.e. wxcc will be taken as the tag on npmjs
> fix(release): update-pipeline-to-new-branch-name

- package-lock.json
- package.json
* The issue was arising in the meetings widget, when a user moved VO over the `Join Meeting` button and they were getting a wrong test - namely saying the state of the mute and video button. (for eg. mute, video on)
* This was causing confusion to the users
* The reason this was not working was because the aria-label of the buttons was taking only the `hint` variable of the components and not reading from the text.
* Further, the hint was coming as null, hence code was added to just take the text as the required label.
* Tests were also done to see that older functionality was not broken.
* Components PR - https://github.com/webex/components/pull/846
Vidcast showing the solution - https://app.vidcast.io/share/3a15014f-1445-4492-8b60-248d3ff54323
* Tests were done to ensure the objective …
> fix: updated-to-latest-components

- packages/contact-center/user-state/src/user-state/user-state.presentational.tsx
The earlier PR was of type chore which will make semantic release not publish the widgets. Therefore merging a PR of commit type fix for that
> fix: rename agent state to user state

- .coderabbit.yaml
Create coderabbitai yaml file to configure CodeRabbitAI
> chore(coderabbit): create .coderabbit.yaml

- .gitignore
- copy_to_docs.sh
- widgets-samples/index.html
While running in amplify sed command doesnt work and causes index.html to redirect to localhost/ not update.
- Removed sed command
- Hardcode href paths in index.html
- add docs/ in gitignore
> fix(samples): change samples index html hrefs

- packages/contact-center/station-login/src/helper.ts
- packages/contact-center/station-login/src/station-login/index.tsx
- packages/contact-center/station-login/src/station-login/station-login.presentational.tsx
- packages/contact-center/station-login/src/station-login/station-login.types.ts
- packages/contact-center/station-login/tests/helper.ts
- packages/contact-center/station-login/tests/station-login/index.tsx
- packages/contact-center/station-login/tests/station-login/station-login.presentational.tsx
- packages/contact-center/store/src/store.ts
- tooling/src/publish.js
- tooling/tests/publish.js
- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- Skipped tests
- Updated UI with material design, dark theme and light theme
> fix(cc-station-login): material design ui

- package.json
- packages/contact-center/cc-components/package.json
- packages/contact-center/cc-components/src/components/UserState/user-state.scss
- packages/contact-center/cc-components/src/components/UserState/user-state.tsx
- packages/contact-center/cc-components/src/components/UserState/user-state.types.ts
- packages/contact-center/cc-components/webpack.config.js
- packages/contact-center/station-login/package.json
- packages/contact-center/station-login/webpack.config.js
- packages/contact-center/store/src/store.ts
- packages/contact-center/task/package.json
- packages/contact-center/task/webpack.config.js
- packages/contact-center/user-state/src/user-state/index.tsx
- widgets-samples/cc/samples-cc-react-app/package.json
- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- widgets-samples/cc/samples-cc-wc-app/package.json
- yarn.lock
- Adds Material Redesign to User State component
- Whoever includes the new user state will have to include it with some styling around:
```
<div style={{
width: '200px',
borderRadius: '50%',
}}>
<UserState />
</div>
```
https://github.com/user-attachments/assets/8272f40d-4e35-4dc6-aa7d-40a55c998297
> feat(cc-user-state): material redesign with rona and wrapup status

- packages/contact-center/station-login/src/helper.ts
- packages/contact-center/station-login/src/station-login/index.tsx
- packages/contact-center/station-login/src/station-login/station-login.types.ts
- packages/contact-center/station-login/tests/helper.ts
- packages/contact-center/station-login/tests/station-login/index.tsx
- packages/contact-center/store/src/store.ts
- packages/contact-center/store/src/store.types.ts
- packages/contact-center/store/src/storeEventsWrapper.ts
- packages/contact-center/store/tests/store.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- packages/contact-center/task/package.json
- packages/contact-center/task/src/CallControl/index.tsx
- packages/contact-center/task/src/helper.ts
- packages/contact-center/task/src/task.types.ts
- packages/contact-center/task/tests/CallControl/index.tsx
- packages/contact-center/task/tests/IncomingTask/index.tsx
- packages/contact-center/task/tests/helper.ts
- packages/contact-center/user-state/src/helper.ts
- yarn.lock
The final round of review for the PR -https://github.com/webex/widgets/pull/369
Since we were on a clock these non-blocking comments were left.
- Removed the isAgentLoggedIn local state in station-login
- Reverted worker thread logic for user-state timmer
- Removed webex as dependency in cc-task, exporting the types from cc-store
https://github.com/user-attachments/assets/4f59576a-09fe-48b4-bfd1-114cd4992233
- Changes state from available to any other state and made sure timmer is refreshed
- Refresh with state as available- timmer should start from 0
- Refresh with state as meeting- timmer held the last state change time
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before …
> fix(store): minor-fixes-after-storeEventsWrapper

- packages/contact-center/store/src/store.types.ts
- packages/contact-center/store/src/storeEventsWrapper.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- packages/contact-center/task/src/helper.ts
- packages/contact-center/task/src/task.types.ts
- packages/contact-center/task/tests/CallControl/index.tsx
- packages/contact-center/task/tests/helper.ts
- widgets-samples/cc/samples-cc-react-app/src/App.scss
- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- widgets-samples/cc/samples-cc-wc-app/app.js
- widgets-samples/cc/samples-cc-wc-app/index.html
* In widgets, we were receiving the agent rona related event but we were not handling it in the sample app.
* Code has been added to include a `taskRejectionCallback` handler inside of the widgets store so users can specify their own custom task rejection method
* For our use case, we show a popup whihch allows users to set a state inside of our sample app (this is widgets sample app specific change)
* [Working with WebRTC in web components](https://app.vidcast.io/share/d451f694-43db-407a-9246-5218769f50c3)
* [Working with WebRTC in react components](https://app.vidcast.io/share/cd9e130e-d1fd-4689-bf1a-d733817975e3)
* [Working in EXTERNAL config](https://app.vidcast.io/share/e5a4d7d7-be0f-4018-85f7-f635d8200ce3)
* Tested with webRTC in both web and react components
* Tested with external …
> feat(widgets): added-agent-rona-popup

- tooling/src/publish.js
- tooling/tests/publish.js
- When we run the `yarn version` command there is a spike in resource usage in circleCI because this command is also running yarn install for all the dependencies for each packages, and since we are running this in a loop there are a lot of yarn installs running. This seems to be failing the circleCI pipeline.
- Rather than using yarn version command to update the version, we are using a custom script to achieve that
- Ran the publish command and ensure the custom script is updating the package.json's version
---
Make sure to have followed the [contributing guidelines](https://github.com/webex/webex-js-sdk/blob/master/CONTRIBUTING.md#submitting-a-pull-request) before submitting.
> fix(tooling): remove-version-command-in-publish

- packages/contact-center/store/src/storeEventsWrapper.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- A user is already logged in and on a call and now if a new session is initiated, the custom status is not being set
- This PR fixes that by handling this in the hydrateHandler
- If an existing session is logged out, the status is set back to "Meeting"
https://github.com/user-attachments/assets/26e134b3-f21c-432d-879c-af7ab6a93413
> fix(user-state): custom status on hydration

- .github/workflows/pull-request.yml
This PR adds validations to the Pull_Request CI job to ensure that the right label and title are set in the description. This is to ensure
1. Only those who have write access can trigger Actions on the PR
2. Titles match what semantic-release looks for to ensure we don't run into deployment issues
PR where this was tested: https://github.com/sreenara/widgets/pull/1
1. Created a PR against this branch to ensure the checks start
2. When the label is not added, no checks are run and everything is skipped
3. When the label is added, the title of the PR is checked and ensures that the author has set it correctly, else the remaining pipeline does not run
> chore(tooling): add pull request checks

- packages/contact-center/cc-components/src/components/UserState/constant.ts
- packages/contact-center/cc-components/src/components/UserState/user-state.scss
- packages/contact-center/cc-components/src/components/UserState/user-state.tsx
- packages/contact-center/store/src/storeEventsWrapper.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- packages/contact-center/task/src/helper.ts
- packages/contact-center/task/tests/helper.ts
There were various bugs which needed to be fixed for the `user-state`. List of the issues are shown below
- When in Custom State, when the agent changes the State from UI, the custom state goes away. This should not happen - **This is already working**
- RONA should have a timer but Engage shouldn't. (Test this case) - **This is already working**
- When in Custom State, if there's an event that changes the state, the custom state goes away. Testing Steps: (**Fixed**)
- Login in to two windows
- Jump on a call to see the states change to Engaged
- Refresh one of two windows and see the state going to Meeting in the other window
[For all of the above, the fix is ideally to prioritize Custom State over the Agent desktop state changes and clear it on Wrapup]
- There's no tooltip today on the …
> fix(contact-center): fix bugs listed in CAI-6468

- packages/contact-center/cc-components/src/components/StationLogin/station-login.tsx
- packages/contact-center/cc-components/src/components/StationLogin/station-login.types.ts
- packages/contact-center/cc-components/src/components/task/CallControl/call-control.styles.scss
- packages/contact-center/cc-components/tests/components/StationLogin/station-login.tsx
- packages/contact-center/station-login/src/station-login/index.tsx
- packages/contact-center/store/package.json
- packages/contact-center/store/src/store.ts
- packages/contact-center/store/src/store.types.ts
- packages/contact-center/store/src/storeEventsWrapper.ts
- packages/contact-center/store/tests/storeEventsWrapper.ts
- playwright/login-user-state.spec.ts
- yarn.lock
This PR provides fixes for the following issues:
**1. Team Name Not Persisting on Re-login**
The team name is now correctly set by listening to the CC_EVENTS.AGENT_STATION_LOGIN_SUCCESS event, as it is not available during the initial station login event.
This ensures that on page refresh (or any re-login scenario), the agent's team name is properly initialized and available in the application state.
**2. Duplicate Sign Out Button Removed**
As per the latest Figma design, the second sign-out button (responsible for triggering Station Logout) is no longer needed.
This button has been removed from the UI to avoid confusion and maintain design consistency.
Subscribed to the CC_EVENTS.AGENT_STATION_LOGIN_SUCCESS event to set the agent’s team name using the teamId, ensuring it is correctly …
> fix(station-login): fix-station-login-bugs

- packages/contact-center/store/src/store.ts
The default login option on first login is hardcoded to AGENT_DN in the store, but WebRTC only agents need not have the AGENT_DN login option. 
Setting the default option to a valid option from loginOptions when deviceType is undefined, i.e fresh login.
https://app.vidcast.io/share/d8e67d2a-b77e-44a0-95c7-66018646ca33
- WebRTC only account. 
- All options available account and re-login scenario.
---
> fix: set a valid default device type on initial login

- packages/contact-center/cc-components/src/components/task/CallControlCAD/call-control-cad.styles.scss
- packages/contact-center/cc-components/src/components/task/CallControlCAD/call-control-cad.tsx
- packages/contact-center/cc-components/src/components/task/Task/index.tsx
- packages/contact-center/cc-components/src/components/task/Task/styles.scss
Vidcast link: https://app.vidcast.io/share/fd9dc8bf-91ac-4b30-8fc1-0e744ac552c3
This pull request addresses the issue of overflowing content in multiple widgets when handling long email addresses as the media type. Specifically:
**1. Context of the Issue:**
- In the Incoming Task Widget rendered in toast notifications, when the media type is email and the user's email address is long, the following problems occur:
1. The email icon overflows outside of the container.
2. The email text does not wrap or display an ellipsis, causing layout issues.
- This issue is not limited to the Incoming Task Widget but is also present in the Call Control Widget and the Task List Widget.
**2. Fixes Provided:**
- The overflow issue has been resolved in the Incoming Task Widget, ensuring:
1. The email icon …
> fix(incoming-task): fix-incoming-task-overflow-issue

- widgets-samples/cc/samples-cc-react-app/src/App.tsx
- widgets-samples/cc/samples-cc-wc-app/app.js
- widgets-samples/cc/samples-cc-wc-app/index.html
Adding provision to login with integration environment in widgets samples
< DESCRIBE THE CONTEXT OF THE ISSUE >
added check box in samples page to enable integration env
< DESCRIBE YOUR CHANGES >
Test1).
1) enable integration Env by clicking checkbox
2) select login with webex and click on login with webex => the url should show idbrokerbts....
3) enter username and password it should login and token textbox should be auto filled.
4) click on initWidgets, it should be success and show station login, do station login and it should be success
https://app.vidcast.io/share/aa04573c-ec45-4482-bc40-c14fc05d5f93
Test2).
1) enable integration Env by clicking checkbox
2) go to integratioin dev portal and get a token
3)paste the token and …
> feat(cc-widgets): integ env

- playwright/global.setup.ts
Add logic in globa.setup.ts to read 2 agent's access-token 
Now we have access to PW_AGENT2_ACCESS_TOKEN in playwrihgt ests
- Pipeline tesitng
---
> fix(playwright): add-logic-to-read-agent2-token

- packages/contact-center/cc-components/src/components/task/TaskList/task-list.utils.ts
- packages/contact-center/cc-components/tests/components/task/TaskList/task-list.utils.tsx
- packages/contact-center/store/src/storeEventsWrapper.ts
Not showing wrapup when we transfer call to other agent.
added a guard check for wrapupRequired before we check isNew
Login to cc widgets, get an incoming call, and accept the call, transfer it to other agent , the callcontrol should show wrapup popup.
and incoming call popup should not come when we reload
---
> fix(cc-widgets): Transfer issue fix

- copy_to_docs.sh
- widgets-samples/chat-client-e2e-2.html
- widgets-samples/chat-client-e2e.html
< DESCRIBE THE CONTEXT OF THE ISSUE >
added new chat client for cc widgets e2e testing
< DESCRIBE YOUR CHANGES >
added new chat client for cc widgets e2e testing
---
> fix(cc-widgets): added new chat client for cc widgets e2e testing

- packages/contact-center/cc-components/src/components/task/CallControl/CallControlCustom/consult-transfer-dial-number.scss
- packages/contact-center/cc-components/src/components/task/CallControl/CallControlCustom/consult-transfer-dial-number.tsx
- packages/contact-center/cc-components/src/components/task/CallControl/CallControlCustom/consult-transfer-popover.tsx
- packages/contact-center/cc-components/src/components/task/CallControl/call-control.tsx
- packages/contact-center/cc-components/src/components/task/CallControl/call-control.utils.ts
- packages/contact-center/cc-components/src/components/task/CallControlCAD/call-control-cad.tsx
- packages/contact-center/cc-components/src/components/task/constants.ts
- packages/contact-center/cc-components/src/components/task/task.types.ts
- packages/contact-center/cc-components/tests/components/task/CallControl/CallControlCustom/__snapshots__/consult-transfer-dial-number.snapshot.test.tsx.snap
- packages/contact-center/cc-components/tests/components/task/CallControl/CallControlCustom/__snapshots__/consult-transfer-popover.snapshot.tsx.snap
- packages/contact-center/cc-components/tests/components/task/CallControl/CallControlCustom/consult-transfer-dial-number.snapshot.test.tsx
- packages/contact-center/cc-components/tests/components/task/CallControl/CallControlCustom/consult-transfer-dial-number.tsx
- packages/contact-center/cc-components/tests/components/task/CallControl/CallControlCustom/consult-transfer-popover.tsx
- packages/contact-center/cc-components/tests/components/task/CallControl/call-control.utils.tsx
- packages/contact-center/store/package.json
- packages/contact-center/task/src/helper.ts
- packages/contact-center/task/tests/helper.ts
- yarn.lock
Implement transfer/consult to DialNumber
added one more tab DialNumber with one textbox and button.
Prerequisite: get a call from customer
transfer to dial number(use sreenara's number)
consult to dial number(use sreenara's number)
end consult before answers
consult to dial number(use sreenara's number)
end consult after answers
consult to dial number(use sreenara's number)
after answer consulttransfer
do the above steps for an entrypoint number as well eg: +16266820030
---
> feat(cc-widgets): Transfer to dial number feature added
